import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/layout/Header";
import { Separator } from "@/components/ui/separator";
import Providers from "@/utils/provider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <Providers>
          <Header />
          <Separator className="fixed top-14" />
          {children}
          <ReactQueryDevtools initialIsOpen={true} />
        </Providers>
      </body>
    </html>
  );
}
